server:
  port: 8282

info:
  appName: product-catalog 
  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/catalogdb
    driverClassName: org.mariadb.jdbc.Driver
    username: root
spring.main.allow-bean-definition-overriding: true